### Add Product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "test",
  "price": 150
}

### Get Products
GET http://localhost:3000/products?pageIndex=1&pageSize=10&sortField=price&sort=asc
Accept: application/json

### Get Count
GET http://localhost:3000/products/count

### GET Product by id
GET http://localhost:3000/products/4
Accept: application/json

### Delete Product by id
DELETE http://localhost:3000/products/4

### Delete all products
DELETE http://localhost:3000/products/

### GET expensivest product
GET http://localhost:3000/products/expensivest
Accept: application/json

### GET cheapest product
GET http://localhost:3000/products/cheapest
Accept: application/json

### GET median product
GET http://localhost:3000/products/median
Accept: application/json
